### ISSUE TITLE
Support different base path for urls in component css

### ISSUE THREAD

**Issue by stschroeder** [AndCake/zino#3]
### Problem
Relative urls in a separate component css file are not working, because the component styling gets rendered in the document itself which results in a base path which is not the path where the images reside in. Therefore e.g. urls to images can not be accessed.

### Steps to reproduce
* Go to a component css file
* Add the following to a css rule to a random tag inside the component
```
background: url(../images/logo/logo_mop.svg)
```
* Go to the page where the component is rendered
* Look into the rendered css rule

### Current behaviour
The browser looks for the image in e.g. http://example.com/images/logo/logo.svg

### Expected behaviour
The browser should look for the image in the static path which is e.g. http://example.com/static/images/logo/logo.svg

**Comment by AndCake** [comment]
This has been fixed in commit 5094ea8 and will be released with the next release.

**Comment by stschroeder** [comment]
This solution is not working if the components are gettings build via grunt-zino because grunt-zino escapes the quotes, e.g.
`background: url(\"../images/logo/logo.svg\")`

This results in the following css:
`"background: url(http://absolute-url"../images/logo/logo.svg\")"`
