### ISSUE TITLE
this object inside a child zino component differs after calling setProps on the parent zino component

### ISSUE THREAD

**Issue by stschroeder** [AndCake/zino#4]
### Problem
The `this` object reference inside a zino component (e.g. inside the mount function) is not an `Element` anymore if the component was re-rendered during the `setProps` process of a parent zino component.

### Steps to reproduce
* Create a parent and a child zino component
* In the parent zino component: Call the `setProps` function somewhere.
* In the child zino component: Use a `Element` function (e.g. `getElementsByClassName`).

### Current behaviour
`this` references an object which is not an `Element` anymore:
```
{tagName: “zino-component”, attributes: {…}, children: Array(0), __complexity: 0, __i: “”, …}attributes: {columns: {…}, color: {…}, type: {…}, url: {…}}attrs: {props: {…}, element: {…}, styles: undefined, body: “”, columns: “10", …}beforeLoading: ƒ ()children: []element: {}generateSrcset: ƒ ()generateSrcsetItem: ƒ ()getHost: ƒ ()innerHTML: “<div class=“-shadow-root”></div>“isRendered: falselazyload: ƒ ()loadImage: ƒ ()mounting: trueprops: {}setAttribute: ƒ (attr, val)setProps: ƒ ()shouldLoadImage: ƒ ()tagName: “zino-component”__complexity: 0__i: “”__s: undefinedbody: (...)get body: ƒ get()set body: ƒ set(val)__proto__: Object
```
Therefore calling the function `getElementsByClassName` results in an error:
```
Error: Unable to call mount function for zino-component: this.getElementsByClassName is not a function
    at Array.initializeNode (zino.js:580)
    at trigger (zino.js:88)
    at Object.initializeTag (zino.js:481)
    at zino.js:609
    at Array.forEach (<anonymous>)
    at renderTag (zino.js:608)
    at render (zino.js:454)
    at reRender (zino.js:1058)
```
### Expected behaviour
`this.getElementsByClassName` should not cause an error and should call the corresponding functionality of an `Element` object

**Comment by AndCake** [comment]
this is only a DOM element for the top-level element. Other elements are rendered before they become actual DOM nodes. Therefore DOM functions won't work on sub components within the mount function. Having getElementsByClassName in the mount function usually doesn't make much sense since it accesses the rendered component content. Recommended would be to use the render function for it.
