### ISSUE TITLE
No rerender when using setProps in mount in pre-rendered component

### ISSUE THREAD

**Issue by AlexanderHoffert** [AndCake/zino#7]
Steps:
* component with setProps in mount
* mount pre-rendered instance of that component

Expected:
* component is rerendered

Current:
* component does not trigger rerender

Dev Remark:
* core.js function setProps checks for tag.mounting but not for tag.isRendered

**Comment by AndCake** [comment]
How can the state be different right after prerendering it? There seems to be a logical error in the expectations...
