### ISSUE TITLE
CSS rules for components are rendered too often

### ISSUE THREAD

**Issue by stschroeder** [AndCake/zino#8]
### General Description
If a same component is invoked several times, the defined css rules of it repeats too. It would be better if it's possible to have the rules only one time regardless how many times the component is invoked.

The css file is linked in component in such a way as following code block shows
```
<zino-component>
	<script src="zino-component.js"></script>
	<link rel="stylesheet" href="zino-component.css" />
</zino-component>
```

### Steps to reproduce
Include the mop-image component in parent component or in html such as:
```
<zino-component></zino-component>
<zino-component></zino-component>
<zino-component></zino-component>
```

### Current behaviour
The css rules are rendered as often as the component is used in the document.

### Expected behaviour
The rules should only be set once.

**Comment by AndCake** [comment]
Unable to reproduce. This could be an issue with your server-side rendering. The regular Zino implementation specifically checks for double inclusion of style tags and avoids adding them if they already exist.
